table Age
	lineageTag: 8c895f08-5261-4fae-8eb5-edf23bf268f8

	column 'Age code'
		dataType: int64
		formatString: 0
		lineageTag: db2ad131-b6e8-4b0f-8f05-72b365553519
		summarizeBy: none
		sourceColumn: Age code

		annotation SummarizationSetBy = Automatic

	column 'Establishment Age'
		dataType: string
		lineageTag: 01a7c0e2-cd77-4559-bdca-97babf45a649
		summarizeBy: none
		sourceColumn: Establishment Age

		annotation SummarizationSetBy = Automatic

	partition Age-38f85073-6963-4fb8-86ea-0499c2422142 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Datacamp\Data Modeling in Power BI\Datasets\EstablishmentAge.csv"),[Delimiter=",", Columns=2, Encoding=1251, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Age code", Int64.Type}, {"Establishment Age", type text}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"Age code"})
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

