table Subsector
	lineageTag: c1c8dcb3-686d-484a-bb41-571c3421ecfe

	column 'Subsector code'
		dataType: int64
		formatString: 0
		lineageTag: 0a8ac228-5ab5-4eec-9c08-a0e1248d27df
		summarizeBy: none
		sourceColumn: Subsector code

		annotation SummarizationSetBy = Automatic

	column Subsector
		dataType: string
		lineageTag: b3799372-886f-4496-b69b-ba704de3131a
		summarizeBy: none
		sourceColumn: Subsector

		annotation SummarizationSetBy = Automatic

	column 'Industry group code'
		dataType: int64
		formatString: 0
		lineageTag: 8697c305-5a58-434f-92e5-a799c96adf9a
		summarizeBy: none
		sourceColumn: Industry group code

		annotation SummarizationSetBy = Automatic

	partition Subsector-a7f780c9-67e6-415f-85cc-ac96fdfa2cac = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Datacamp\Data Modeling in Power BI\Datasets\Establishment Survey.csv"),[Delimiter=",", Columns=16, Encoding=1251, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Id", Int64.Type}, {"Age code", Int64.Type}, {"Year", Int64.Type}, {"NAICS code", Int64.Type}, {"Number of firms", Int64.Type}, {"Number of establishments", Int64.Type}, {"Number of employees", Int64.Type}, {"Number of establishments born", Int64.Type}, {"Number of establishments exited", Int64.Type}, {"NAICS code description", type text}, {"Industry group code", Int64.Type}, {"Industry group", type text}, {"Subsector code", Int64.Type}, {"Subsector", type text}, {"Sector code", Int64.Type}, {"Sector", type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"NAICS code", "NAICS code description", "Industry group code", "Industry group", "Subsector code", "Subsector", "Sector code", "Sector"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns", {"NAICS code"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Removed Duplicates",{"Subsector code", "Subsector", "Industry group code"}),
				    #"Removed Duplicates1" = Table.Distinct(#"Removed Other Columns1", {"Subsector"})
				in
				    #"Removed Duplicates1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

